apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: andor
  name: communication-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-manager
  template:
    metadata:
      labels:
        app: communication-manager
    spec:
      containers:
        - name: communication-manager
          image: communication-manager
          ports:
            - containerPort: 80
              name: http
